# Generated by Django 5.1.13 on 2026-01-01 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_genre_game_listing_swapoffer_notification_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="message",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="notification",
            old_name="recipient",
            new_name="recieved_profile",
        ),
        migrations.RenameField(
            model_name="notification",
            old_name="created_at",
            new_name="time",
        ),
        migrations.AddField(
            model_name="notification",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_notifications",
                to="api.profile",
            ),
        ),
    ]
