# Generated by Django 5.1.13 on 2026-01-01 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_rename_message_notification_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HasInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.genre"
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.profile"
                    ),
                ),
            ],
            options={
                "db_table": "hasInterest",
                "unique_together": {("profile", "genre")},
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="interests",
            field=models.ManyToManyField(
                blank=True,
                related_name="interested_profiles",
                through="api.HasInterest",
                to="api.genre",
            ),
        ),
    ]
