# Generated by Django 5.1.13 on 2026-01-08 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_hasinterest_profile_interests"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bgg_id", models.IntegerField(unique=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("min_players", models.IntegerField(blank=True, null=True)),
                ("max_players", models.IntegerField(blank=True, null=True)),
                ("playing_time", models.IntegerField(blank=True, null=True)),
                ("min_playtime", models.IntegerField(blank=True, null=True)),
                ("max_playtime", models.IntegerField(blank=True, null=True)),
                ("year_published", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("image_url", models.URLField(blank=True, max_length=500)),
                ("thumbnail_url", models.URLField(blank=True, max_length=500)),
                ("rank", models.IntegerField(blank=True, null=True)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("complexity", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="game",
            name="board_game",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_games",
                to="api.boardgame",
            ),
        ),
    ]
