# Generated by Django 5.1.13 on 2026-01-08 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_boardgame_game_board_game"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="complexity",
        ),
        migrations.RemoveField(
            model_name="game",
            name="number_of_players",
        ),
        migrations.RemoveField(
            model_name="game",
            name="playing_time",
        ),
    ]
