# Generated by Django 5.1.13 on 2026-01-08 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_remove_game_complexity_remove_game_number_of_players_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="name",
        ),
        migrations.AlterField(
            model_name="game",
            name="board_game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_games",
                to="api.boardgame",
            ),
        ),
    ]
