# Generated by Django 5.1.4 on 2026-01-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_remove_game_name_alter_game_board_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
