# Generated by Django 5.1.4 on 2026-01-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(choices=[('GENRE1', 'Genre1'), ('GENRE2', 'Genre2'), ('GENRE3', 'Genre3'), ('GENRE4', 'Genre4')], default='GENRE1', max_length=20),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(choices=[('GENRE1', 'Genre1'), ('GENRE2', 'Genre2'), ('GENRE3', 'Genre3'), ('GENRE4', 'Genre4')], default='GENRE1', max_length=20),
        ),
    ]
