# Generated by Django 5.1.4 on 2026-01-10 22:24

from django.db import migrations

def create_genres(apps, schema_editor):
    # Dohvaćamo model Genre iz povijesti migracija
    Genre = apps.get_model('api', 'Genre')
    
    # Lista tvojih žanrova iz modela
    GENRES = ["PUZZLE", 
        "COOP", 
        "STRATEGY", 
        "TRIVIA",
        "RPG",
        "CHALLENGE", 
        "CARD"]
    
    for name in GENRES:
        Genre.objects.get_or_create(name=name)

def remove_genres(apps, schema_editor):
    Genre = apps.get_model('api', 'Genre')
    Genre.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_game_genre'),
    ]

    operations = [
        migrations.RunPython(create_genres, remove_genres),
    ]