# Generated by Django 5.1.4 on 2026-01-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_pushsubscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(
                choices=[
                    ("PUZZLE", "Mozgalica"),
                    ("COOP", "Kooperativna igra"),
                    ("STRATEGY", "Strateška"),
                    ("TRIVIA", "Opće znanje"),
                    ("RPG", "Igranje uloga"),
                    ("CHALLENGE", "Izazovi"),
                    ("CARD", "Kartaška igra"),
                ],
                default="GENRE1",
                max_length=20,
            ),
        ),
    ]
