# Generated by Django 5.1.4 on 2026-01-14 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_genre_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_sent', to='api.profile')),
                ('target_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to='api.listing')),
            ],
        ),
    ]
