# Generated by Django 5.1.4 on 2026-01-15 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_wishlist_board_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='description',
        ),
    ]
